<?php

/**
 * @file
 * Contains bitly_links.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bitly_links_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bitly_links module.
    case 'help.page.bitly_links':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Generates bitly links.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bitly_links_theme() {
  return [
    'bitly_links' => [
      'render element' => 'children',
    ],
  ];
}
